FROM ubuntu:16.04

MAINTAINER Geoff Stockham (geoff@stormid.com)

# Stripped back version of the google docker image

# Pick up some TF dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python \
        python-dev \
        rsync \
        software-properties-common \
        unzip \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip --no-cache-dir install \
        numpy \
        scipy \
        pillow \
        flask \
        flask-restful \
        tensorflow

WORKDIR "/code"

EXPOSE 5000

CMD ["/app.py"]